application:
  title: 数据接收服务
  version: 1.0.0.RELEASE
netty:
  url: 0.0.0.0
  port: 8001
spring:
  application:
    name: monitor-center
  datasource:
    dynamic:
      primary: master
      datasource:
        #数据源1
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://url:3306/master?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: *******
        #数据源2
        environmental:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://url:3306/environmental?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: *******
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/cache/ehcache.xml
mybatis-plus:
  configuration:
    local-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**.xml
  global-config:
    db-config:
      id-type: id_worker_str
    banner: false
logging:
  config: classpath:config/log/logback-spring.xml
